### ISSUE TITLE
Content-Security-Policy should use default-src 'none'.

### ISSUE THREAD

**Issue by ronperris** [pillarjs/finalhandler#26]
# What I expected
The Content Security Policy would deny loading resources by default.

# What I experienced
The Content-Security-Policy uses 'self', which is more permissive than 'none'.

# Why does this matter?
The Content-Security-Policy currently sets the following directives to permit loading from self.

child-src
connect-src
font-src
frame-src
img-src
manifest-src
media-src
object-src
prefetch-src
script-src
style-src
worker-src

There is no reason to allow all this functionality since the error page doesn't use any of these browser features. The current input validation and escaping code prevent tampering with the page contents, but if a bypass was found the Content Security Policy is needlessly permissive, IMHO. Set the default-src directive to 'none' and the page will continue to function and another layer of defense will be enabled.

**Comment by dougwilson** [comment]
Thanks! I set the value to this just because it is what a security researcher suggested. If there is a more restrictive and it works with all the possible outputs, feel free to make a pull request :)

**Comment by dougwilson** [comment]
Clicked on the wrog button to leave a comment,  I apologize.

**Comment by oreoshake** [comment]
Because CSP is non-obvious `default-src 'self'` allows flash, java, xss/jsonp abuse - 3 things modern web development shouldn't be using, are inherently dangerous, and have more or less been replaced by more modern technologies.

**Comment by ronperris** [comment]
@dougwilson Will this PR work for you?

**Comment by dougwilson** [comment]
Hi @ronperris sorry I've just been away traveling to a hackathon to help students learn open source :) ! So haven't had the opportunity to take a look just yet.

**Comment by ronperris** [comment]
@dougwilson Would you be open to releasing this soon? I ran into this issue because I was using another library and this functionality was downgrading my defined CSP policy.

**Comment by dougwilson** [comment]
Yes, I can. Typically these are coordinated with express releases but it's not required. The other lib that is using this is not express, is it?

**Comment by ronperris** [comment]
@dougwilson I was using https://github.com/helmetjs/helmet to set policy and they were being downgraded in finalhandler.

**Comment by dougwilson** [comment]
I see, though helmet doesn't use the finalhandler module. Just curious on where in your setup this module is getting invoked.

**Comment by ronperris** [comment]
@dougwilson Sorry, it is express. I was using helmet with express.

**Comment by dougwilson** [comment]
Ok. So even if a new version of this module is released, you still won't see the behavior change until a new version of express is release. Since this is a new feature, it would be bundled with the in progress express 4.17 release, which is still in progress, though it's being closed in on.

That being said, ideally your express app would never invoke this module by having a custom-defined 404 and error handler to generate the output for those as you would like instead of relying on the default catch-all (this module).

So it sounds like the release of this module will stay on its current course: it will get a new release bundled with express, as that is what you'd need anyway.

**Comment by youngbob** [comment]
This has just been published as an npm advisory: https://www.npmjs.com/advisories/836
So, any upstream users of this module (which includes any users of express, react-scripts) are going to start seeing vulnerability reports when running npm/yarn audit. Please publish a new version of this module with the fix, so users can upgrade to a fixed version (even if that involves forcing the resolution in yarn until express also updates).

**Comment by dougwilson** [comment]
This is not a vulnerability? How can the module author not be involved in any of the publishing of an advisory? I wasn't even aware this would be an advisory at all...

**Comment by youngbob** [comment]
Sorry, I wasn't involved in publishing this, I just ran into this when running one of my own builds and thought I should mention something here.

**Comment by dougwilson** [comment]
Like I still need a few more days to wrap up the Express 4.17 release. Perhaps if there was some sort of coordination? @ronperris  ?

**Comment by dougwilson** [comment]
It's no problem @youngbob . I would have absolutely had a new version published before an advisory was published had I known an advisory was even going to be published (and ideally on what date). But I had no idea and now it's published.

I'm also unclear on what, specifically, the vulnerability is? Like there is no method to get arbitrary HTML onto the responses in this module, so it's not like there is a method to do anything?

Like is the issue that there isn't the most strict `Content-Security-Policy` header on responses? If so, then it would seem like many, many packages across npm would have this issue, as most never even set this header, and this module doesn't set the header on responses it doesn't produce.

Or is the issue that this module is producing a `Content-Security-Policy` _and_ it's not the most strict it could be? If so, then I would assume that the old versions of this module that never set this header would not be marked as vulunerable, but yet the linked advisory has them marked as vulunerable.

Can you help us @ronperris ? I se you're also listed in the HackerOne report, perhaps you can provide clarity here.

**Comment by dougwilson** [comment]
Maybe @lirantal or @vdeturckheim would be able to help here as well, as they are usually active in the Node.js security stuff.

A sudden drop on a Friday evening (my time, but still a Friday across the world) makes it that much harder to get addressed in a timely manor, even ignoring the lack of prior notification to the module author (myself) that it was going to be appearing.

**Comment by youngbob** [comment]
For what it's worth, I'm 100% on your side here. I suggest emailing security@npmjs.com about how this was handled. Considering the number of upstream users that are going to be seeing this, maybe it will get someone's attention.

**Comment by dougwilson** [comment]
Thanks @youngbob I just wrote up an email and sent it off.

**Comment by 73rhodes** [comment]
Suggest re-opening this issue pending resolution to https://github.com/pillarjs/finalhandler/issues/26

**Comment by dougwilson** [comment]
As an update I have not gotten a response from npm security so far, besides an automated email confirmed my email was received. It's possible that the email is only active during business hours, so it may not be until Monday at the earliest for a resolution to begin.

**Comment by dougwilson** [comment]
Still no response from anyone, as an update.

**Comment by dougwilson** [comment]
Still no response from npm security. Not sure how to get a response in order to move forward over the weekend. @jasnell maybe has contacts around who could help? The TL;DR is that npm has suddenly added an advisory on this module with no prior notice and marked all current and future version of the module vulnerable.

**Comment by jasnell** [comment]
Hmm... I'm not near my laptop at the moment and phone will be dying soon. I'll make a note to check on this later today.

**Comment by mgibeau** [comment]
If I understand correctly, the fix is in the master branch, if you were to release a new version, do you think it would still get flagged as vulnerable?

Personally, I use `yarn` instead of npm, and it allows to fix vulnerable dependencies, by doing something like:

```
  "resolutions": {
    "finalhandler": ">=1.1.1"
  },
```

**Comment by dougwilson** [comment]
@mgibeau yes, because npm has marked the version range as `*` to include new versions until they review. If the fix is truly in master, then the version range in npm security is still wrong, because it wouldn't affect the older versions. That's why I'm waiting to hear from them the specifics so I can (1) get the version range corrected and (2) _ensure_ that the release includes the fix they are looking for instead of guessing, especially since the next version will still be marked vulnerable anyway.

You can see another module like this here: https://www.npmjs.com/advisories/827 . npm added a `*` range to that module on Apr 19th (just like it did not this module on May 3rd) and even though it's fixed in 1.1.7 and 1.2.0 (published Apr 22nd) npm still shows those as vulnerable (https://www.npmjs.com/advisories/827/versions) as it's listed to blacklist the module, just the same as this advisory is set up.

**Comment by mgibeau** [comment]
Ok, thanks, that's too bad then... Hopefully they can resolve this soon🤞

**Comment by dougwilson** [comment]
Yea, me too. Still no response to my email, at this time.

**Comment by jasnell** [comment]
I just sent an email also. Will see if I have any more luck getting a response. It does seem a bit odd that you wouldn't have been given a heads up before the advisory was published.

**Comment by dougwilson** [comment]
Right. And as far as I know this is not even a vulnerability. You can see the linked HackerOne (I also didn't know existed until the advisory was published) is set to None for the severity right before it it opened.

**Comment by dougwilson** [comment]
For reference the only conversation that happened regarding this is in this issue; there were no other methods, emails, etc. I assume there was no heads up on the HackerOne is because it was not marked as a vulnerability, and the was nothing i  this issue the ever indicated it was a vulnerability.

I can only assume that there is someone on the npm security team who watched HackerOne, saw the issue open to public, and just assumed it was a vulnerability and blacklisted the module and assumed that since there was an issue here they needed provide no notice 

That is just speculation, but IDK what else to think without some kind of follow up from someone...

**Comment by ronperris** [comment]
@dougwilson Here is the H1 report related to this issue. https://hackerone.com/reports/504931

As you correctly pointed out, this isn't a vulnerability but an insecure default configuration with its risk set to 0 and weakness level set to none.

I triaged this in H1 as a potential issue, but it never got listed as a vulnerability in the workgroups vulnerability list. https://github.com/nodejs/security-wg/tree/master/vuln/npm

It looks like NPM decided to use the H1 activity instead of the published list as their information source and upgraded the vulnerability from `none` to `low. https://www.npmjs.com/advisories/836

**Comment by dougwilson** [comment]
Thanks @ronperris . Can you help clarify some of the details here by responding the the questions in https://github.com/pillarjs/finalhandler/issues/26#issuecomment-489243950 as well?

**Comment by ronperris** [comment]
@dougwilson Where can help add clarity? Please help me surface any unanswered questions if you have the bandwidth.

**Comment by dougwilson** [comment]
Hi @ronperris , the link in my comment should take you to the comment with my questions. Here they are again:

> I'm also unclear on what, specifically, the vulnerability is? Like there is no method to get arbitrary HTML onto the responses in this module, so it's not like there is a method to do anything?

> Like is the issue that there isn't the most strict Content-Security-Policy header on responses? If so, then it would seem like many, many packages across npm would have this issue, as most never even set this header, and this module doesn't set the header on responses it doesn't produce.

> Or is the issue that this module is producing a Content-Security-Policy and it's not the most strict it could be? If so, then I would assume that the old versions of this module that never set this header would not be marked as vulunerable, but yet the linked advisory has them marked as vulunerable.

> Can you help us @ronperris ? I se you're also listed in the HackerOne report, perhaps you can provide clarity here.

**Comment by ronperris** [comment]
@dougwilson Are these not answered in my original comment? Sorry if I come across as difficult here, I just want to avoid duplicating information that is already stated.

**Comment by dougwilson** [comment]
Hi @ronperris , as far as I can tell, no. Feel free to quote the responses in the original comment if it answers them, as perhaps I am overlooking it. I also read through the HackerOne report and it is not clear. Like for example, is the following an insecure default configuration, as it allows scripts, etc. to be executed?
```js
var http = require('http')

var server = http.createServer(function (req, res) {
  res.end('hello, world!')
})

server.listen(3000)
```

The above results in no `Content-Security-Policy` header, allowing XSS, embedded scripts, etc.

**Comment by ronperris** [comment]
@dougwilson Thank you helping me see the ambiguity. 

The security issue is that a CSP header was added to the default error handler as a "defense-in-depth" measure, it was never meant to address a known vulnerability, you stated that `I set the value to this just because it is what a security researcher suggested.`

I suggested a more secure header configuration that would improve the CSP policy.

I see a couple alternatives that could have happened here instead of accepting my PR.

1.) You could have told me that you like the current CSP policy and didn't want to improve it. You are the maintainer and I think that is your call to make.

2.) You could have removed the CSP header completely because you didn't see a vulnerability that it directly mitigated at this time. 

CSP is a "defense-in-depth" measure and is in place to protect you when other mechanisms fail. Having the strictest policy possible as the default policy is a valid approach.

If a script sink is ever added to that page the new CSP `default-src: none` will protect that page from script execution.

CSP is always a good idea on any HTTP response.

**Comment by dougwilson** [comment]
Gotcha. So there is a HackerOne that says "insecure default configuration" but the contents of that HackerOne do not lay that out. I'm trying to understand, specifically, what the "insecure default configuration" is, to (a) help me audit the rest of my modules (b) help present the case to npm about the report on their site.

Is the example I provided "insecure default configuration" yes or no? You didn't really answer that?

Also, are you saying that by not accepting your PR we would not be in this situation, as in there is no vulnerability even without accepting the PR? As in, is the npm security assessment correct or not? If it is correct, then why does it apply to versions that never set the `Content-Security-Policy` header (versions less than 1.0.0)?

**Comment by evilpacket** [comment]
@dougwilson This just came across my desk. I'm reading scrollback and checking our security inbox to see what needs to be done on our end.

**Comment by dougwilson** [comment]
> You could have removed the CSP header completely because you didn't see a vulnerability that it directly mitigated at this time.

Based on this, since there is nothing in this module that can result in scripts getting written on the page, are you saying that the current patch on `master` is actually the incorrect solution? That instead the `Content-Security-Policy` header should be removed from this module, as it is not mitigating anything?

**Comment by ronperris** [comment]
@dougwilson 

> Is the example I provided "insecure default configuration" yes or no? You didn't really answer that?

I'd like to stick to talking about finalhandler, if possible, rather than other code or example apps.

> Also, are you saying that by not accepting your PR we would not be in this situation, as in there is no vulnerability even without accepting the PR? 

If you had rejected my PR and closed this issue without changing the code then I would have closed the HackerOne report and documented that you were not interested in improving the security mechanism. This happens.

> As in, is the npm security assessment correct or not? 

The Node Security WG didn't not publish a vulnerability in finalhandler. We have list of those [here](https://github.com/nodejs/security-wg/tree/master/vuln/npm). 

NPM published a `low` risk vulnerability in finalhandler, you would have to ask them why.

> If it is correct, then why does it apply to versions that never set the Content-Security-Policy header (versions less than 1.0.0)?

Great point, this is question for NPM> The report on HackeOne only talks about version 1.1.1.

**Comment by ronperris** [comment]
> Based on this, since there is nothing in this module that can result in scripts getting written on the page, are you saying that the current patch on master is actually the incorrect solution? That instead the Content-Security-Policy header should be removed from this module, as it is not mitigating anything?

CSP is a "defense-in-depth" measure and is in place to protect you when other mechanisms fail. Having the strictest policy possible as the default policy is a valid approach.

**Comment by evilpacket** [comment]
@ronperris we published a vulnerability in this module because of this HackerOne issue that was made public. The issue shouldn't be disclosed on HackerOne if it's not intended to be imo.

We have found that there is significant lag in some cases between when issues are made public on HackerOne and then are imported into the security-wg db so we monitor both.

**Comment by evilpacket** [comment]
@dougwilson I have made the advisory private in the npm advisory db for now until we can resolve what needs to take place.

**Comment by dougwilson** [comment]
@ronperris so you're saying that any HTTP response that does not include a `Content-Security-Policy` header is a vulnerability of "insecure default configuration"? The discussion of this in general is very necessary, because I need to update all of Express to include this, and there are other parts of Express that do not set this header, and doing a release to fix this, but not in a holistic way doesn't make sense.

**Comment by ronperris** [comment]
@dougwilson 

I'm saying that if you set a security header, you should set it correctly or leave it out entirely.

**Comment by dougwilson** [comment]
@ronperris but when I said that if I just changed this module to remove it, you'd still consider that an issue?

**Comment by ronperris** [comment]
> @ronperris but when I said that if I just changed this module to not include the header, you'd still consider that an issue?

Sorry, where did I say that?

**Comment by dougwilson** [comment]
@ronperris https://github.com/pillarjs/finalhandler/issues/26#issuecomment-489371786

**Comment by ronperris** [comment]
@dougwilson 

Are you referring to `Having the strictest policy possible as the default policy is a valid approach.`?

Here I'm saying that if you have CSP policy, which you have in this case, you should have the strictest policy possible.

**Comment by dougwilson** [comment]
Gotcha. So it seems like the safest approach here is to _remove_ the `Content-Security-Policy` HTTP header from all my modules, in order to not have to play this wack-a-mole? In this way, with no header being set, then there will not be a vulnerability, since not having it set is therefore safer than having it set to one that is not as strict as possible, it seems.

**Comment by ronperris** [comment]
@dougwilson 

If you don't want the protection that CSP provides, feel free to remove it. Leaving CSP in and misconfigured is not ideal, which is why I opened this issue and sent you a PR to fix it.

**Comment by isaacs** [comment]
@dougwilson I read this as, a module providing a default CSP header is a signal to a user that it's doing security, and having the defaults be insecure is thus a problem.  If you don't put a lock on your door, you know it's unlocked.  But if I give you a door with a shoddy lock, you might assume you're protected when you aren't, which is worse.

@ronperris or @evilpacket can correct me if I'm getting that wrong.

**Comment by dougwilson** [comment]
Thanks @evilpacket

**Comment by dougwilson** [comment]
Thanks @isaacs that seems like the statement being made here as well. This seems like the most correct solution here is to _stop setting the `Content-Security-Policy` header, like the versions prior to 1.0.0 did. Is there agreement on this being the correct solution?

**Comment by ronperris** [comment]
@evilpacket 

> we published a vulnerability in this module because of this HackerOne issue that was made public. The issue shouldn't be disclosed on HackerOne if it's not intended to be imo.

> We have found that there is significant lag in some cases between when issues are made public on HackerOne and then are imported into the security-wg db so we monitor both.

It makes perfect sense to monitor alternative channels for information, but taking that information and upgrading the risk level and affected versions seems to be the issue here.

**Comment by evilpacket** [comment]
@ronperris yes I agree. I recognized this after I wrote that (see the DM I just sent to you). I think that it was likely that an analyst missed that it was set from Low to None for severity. Which isn't very clear at all in the HackerOne disclosure timeline imo.

**Comment by ronperris** [comment]
@dougwilson 

Notice that sites like Google and GitHub have CSP but no known vulnerabilities.

**Comment by ronperris** [comment]
@evilpacket Thanks for your help on this one.

**Comment by dougwilson** [comment]
So what is the path for https://www.npmjs.com/advisories/836 ? Does everyone agree or disagree on the proposed solution in https://github.com/pillarjs/finalhandler/issues/26#issuecomment-489372650 ? I would like to get a statement out for all the affected Express users who have been asking about this issue, and there are similar issues like this in some of my other modules, so I'm trying to get them solved, but refusing to talk about the issue outside of this module @ronperris , rather than the root issue, is not helpful, in fact, it feels outwardly hostile, to be honest.

**Comment by ronperris** [comment]
@dougwilson 

You can call me hostile, ad hominem, but it seems that you've agreed with the refined points I've made about this particular case. I was just trying to discuss this particular case and be helpful and accurate.

**Comment by evilpacket** [comment]
My thought is it looks like if was disclosed on HackerOne with a `none` severity.

I would argue you can't have a vulnerability with a `none` severity so if it is an issue it's `Low` and then we would pin the advisory to specific version. We do have the ability to issue Informational advisories but we have no yet to date, those are more for footguns, "if you hold it this way it can make this vulnerable" but again haven't used it yet.

imo if you can unset the header as opposed to having a weak header then we can pin an advisory and give people an upgrade path.

**Comment by ronperris** [comment]
@dougwilson I'm a huge fan of yours and Express. 

If that helps to better understand my perspective, I am trying to be helpful.

**Comment by dougwilson** [comment]
It feels hostile as in the following is how I have experienced events:

1) I get a report from you (this issue) in the public, just as a general question.
2) You offer a PR to make the value stricter.
3) You ask when it'll be released and I gave a general answer and no further clarification was asked for.
4) No indication that this was a vulnerability of any kind.
5) I have been working towards the agreed upon release in good faith
6) Suddenly there is a vulnerability disclosed on this, showing up in npm audit, which is a default feature with no noticed what so ever.
7) I try to get in contact as soon as I can, but nothing.
8) In floods issues, emails, DMs from understandable frustrated end users.
9) No responses...

I don't think you understand that when this happens, I literally get hate emails to my email address. I removed my email address from GitHub, but they still get it. Here is a literal quoted email:

> Fucking release an express that does not have a security vulnerability out of the box. I can no longer check in code to my company CI because audit blocks it. Get off your ass.

**Comment by ronperris** [comment]
> Suddenly there is a vulnerability disclosed on this, showing up in npm audit, which is a default feature with no noticed what so ever.

I didn't make this happen. I didn't publish a vulnerability in finalhandler the NPM team did.

**Comment by dougwilson** [comment]
> I didn't make this happen. I didn't publish a vulnerability in finalhandler the NPM team did.

Right, I get that now, but how am I supposed to know that at the time? The npm site lists that you were the reporter on May 3rd, so it made it sound like you reported it to npm on May 3rd. What else was I supposed to interpret that as?

![image](https://user-images.githubusercontent.com/67512/57185987-d0e6f680-6ea4-11e9-9962-aabeec450960.png)

**Comment by ronperris** [comment]
@dougwilson I accept your apology.

**Comment by evilpacket** [comment]
@dougwilson we monitor the hackerone feed from the security-wg, and issued an advisory but failed to see it as a none severity. Note this was human error was we do not automatically import from there into our db. I have now removed the advisory until we can decide what versions are impacted or if we even want the advisory to exist.

My plan here is to discuss on Monday our process for disclosure in npm audit to ensure that maintainers are aware regardless of what communications happens via the security-wg.

**Comment by evilpacket** [comment]
@dougwilson as an aside I'm very sorry for the hate that was directed towards you because of this. You do a lot of good work and maintain a lot of OSS that I've relied on and I'm grateful for this.

**Comment by dougwilson** [comment]
Yes, @ronperris I give my apology to you. Since the bombardment has started, I admit that it has affected me, and I may not be of the right mind...

Really, I just want to get this over with and get a fix out that is acceptable to resolve the situation.

To summarize, it sounds like the right solution here is just to remove the `Content-Security-Policy` header from this module, and the other modules in Express currently also only setting it to `'self'` and not to `'none'` such that it removes the false sense of security the header existing is providing. This way I can get a 4.17 express release cut such that nowhere in it is it providing the not-the-strictest-possible CSP headers. Is this correct?

**Comment by ronperris** [comment]
@dougwilson Thank you for all the work you do on these critical projects. I admire you and hope to make contributions that are more valued going forward.

For this case, I understand if you want to remove CSP from Express and its related modules. Let other modules dedicated to setting security headers handle it, like helmet.

**Comment by dougwilson** [comment]
Thanks @ronperris . The header (and even their specific value) were all added from another security researcher saying they should be there. I just hope that I am doing the right thing, as it just feels like I am at the mercy of the whims of whatever the different security researchers want, because if I do nothing, then the module ends up blacklisted, but if I do something, then maybe it now results in a new issue.

The landscape in this regard has changed so significantly from when I first started, that it has actually becomes the biggest friction point to maintaining modules in Node.js...

**Comment by ronperris** [comment]
@dougwilson Express is so massively successful that you will continue to get targeted by researchers and users reporting issue with security settings, I know you already know that.

I have a deep interest in Express and its security, if you ever need to off load any work I'm free to help.

**Comment by dougwilson** [comment]
Thank you. What I need help with is fi we can determine the final solution in regards to this issue and get some form of double jeopardy protection in regards to it. For example, if I remove the `Content-Security-Policy` header, is it possible such that there can no be another hearing on this issue in the future? As in the solution here is marked as the final ruling i.r.t. the CSP header on this module? I fear that removing the header could case the same or others to come claiming security vulnerability due to the lack of the header. The processes around the judgements i.r.t. ecosystem security issues feels like a black box.

For instance, I didn't know this issue had a backing HackerOne report and that it would be disclosed (which in turn caused confusion with npm security). Ideally Synk and others are not confused and I have to go through this entire dance all over again... but npm security points out having the open vulunerability listed on HackerOne is a point of confusion.

So like I guess what I'm asking here is together we should determine the following

1) What is the final judgement w.r.t. this module and the CSP header
2) Can this judgement be enforced by the node security-wg to prevent a double jeopardy like situation in the future?
3) What is going to happen with the npm advisory listing?
4) What is going to happen with the HackerOne report?

**Comment by dougwilson** [comment]
So now SourceClear has picked up this issue: https://www.sourceclear.com/vulnerability-database/security/insecure-content-security-policy-csp/javascript/sid-13708/ and everyone using SourceClear to check their modules are now showing as a Medium security issue.

**Comment by dougwilson** [comment]
I should just disappear from GitHub / Node.js at this point... I can't catch a break and even enjoy this weekend :(

**Comment by dougwilson** [comment]
Ok, so since there hasn't been any response to my questions above, and it does sound like it won't be until Monday for a decision to be made, I am going to turn off my email and GitHub until Monday at minimum so I do not have to be harassed with users who cannot get express installed due to this. Please do not email me, as I have a filter to trash everything for now and I'm not going to dig through the trash even after I remove it because I just don't want to read the harassing emails.

For those who are able to follow though the linked issues and come upon this, I have locked this issue to make sure that while I'm going to be offline this notice remains at the bottom and can be found and read:

There is an ongoing discussion on the issue here for finalhandler. I am sorry that you cannot get express, connect, karama, brave, or whatever else includes express/connect installed due to this issue. I had no idea this was classified as a security vulnerability before it was published and I was blind-sided. There is still not a specific agreement on what the fix should be, which is why there is no new version yet.

**Comment by dougwilson** [comment]
> if you ever need to off load any work I'm free to help.

@ronperris if you really stand by this offer, please help get the https://www.sourceclear.com/vulnerability-database/security/insecure-content-security-policy-csp/javascript/sid-13708/ removed, as they told me they will not as long as the HackerOne report is there as reports are vulnerabilities. They make it sound like it's your report that they made the issue and will not take it down unless maybe you contact them as you are the security researcher they are basing it off.

**Comment by dougwilson** [comment]
I have requested the Security-WG to take down the HackerOne report and reto on why the HackerOne process was not followed: https://github.com/nodejs/security-wg/issues/527

**Comment by dougwilson** [comment]
Due to the conversancy around this issue, the merged PR will be backed out and a release made without it, keeping the behavior intact. An internal issue within the Express TC will be opened to determine the method in which this should be resolved: lock the header down or remove the header. There was no clear answer provided by the security researcher in this regard and I don't think there will be, so the Express TC as a whole will make the call. In the thread above, the question presented was the following:

> To summarize, it sounds like the right solution here is just to remove the Content-Security-Policy header from this module, and the other modules in Express currently also only setting it to 'self' and not to 'none' such that it removes the false sense of security the header existing is providing. This way I can get a 4.17 express release cut such that nowhere in it is it providing the not-the-strictest-possible CSP headers. Is this correct?

The response was not a yes/no, instead it was the following:

> For this case, I understand if you want to remove CSP from Express and its related modules. Let other modules dedicated to setting security headers handle it, like helmet.

This makes it sound like a "yes" to remove the header completely, in order to "[...] Let other modules dedicated to setting security headers handle it, like helmet."

**Comment by jasnell** [comment]
Fwiw, @dougwilson, I think removing the header is the best course of action at this point

**Comment by dougwilson** [comment]
Though the npm security advisory has been removed (perminently or temporarily, I'm not sure of yet), the SourceClear listing will not be removed. I got an email response that they disagree with the HackerOne report severity level and their report will stand. I'm sorry about this situation.

There is active discussion for the resolution here in the Express security repository. There are multiple people from multiple time zones, so it will take at least a bit more to reach a consensus.
