### ISSUE TITLE
If misused, this library can cause problems writing responses.

### ISSUE THREAD

**Issue by timexcession** [pillarjs/finalhandler#38]
We have a series of express error handlers in our application, some of which need to call `next` after writing the response.

This causes `finalHandler` to crash the application, as it writes a response that is already written.

It took a long time to debug this. 

It would be nice to have a guard clause - `if (res.complete) return` at the appropriate point in this middleware.

Of course, I've fixed this in our app for now, by adding that as a final middleware in our app - before `finalHandler` gets a look in.
Nevertheless this could be a good safety feature.

**Comment by dougwilson** [comment]
Hi @timexcession sorry for the issue you are having. This module should already be performing such a check though the use of a dependency. Perhaps it is not working correctly, though. Can you provide a reproduction case that demonstrates the issue?

**Comment by timexcession** [comment]
Thanks for the quick response Doug! Amazing!

Node 16.13.0

I can't reproduce this in a simple app and I have a work around so -  not sure where to go. Definitely did isolate it to this finalHandler with a use case a bit like this, but there's a lot more going on.
```
const express = require('express');
require('express-async-errors');

const app = express();

app.get("/", [async (req,res,next)=> {
    await new Promise(r => setTimeout(r,100) );
    throw new Error("broken")
}, (err,req,res,next)=>{
    throw err
}]);

app.use(async (err, req, res, next )=>{
    res.status(500).end(err.message);
    next(err);
});
```

**Comment by dougwilson** [comment]
Hi @timexcession thanks for the response. So without a reproduction, it is hard to know where exactly such a guard should be placed in this module, I hope you understand. That plus being able to add to our test suite to verify fix and non-reoccurrance.

What I can say, though, based on your example, is that the check may actually need to be in your own code, possibly. That is because when you can `next(err)` where `err` is truthy, this module will actually terminate a response that is already in progress, and if your code continues to try to write, it my encounter an error from doing so.

https://github.com/pillarjs/finalhandler#finalhandlerreq-res-options

> If it is truthy, [...] res will be terminated if a response has already started.

http://expressjs.com/en/guide/error-handling.html#the-default-error-handler

> If you call next() with an error after you have started writing the response (for example, if you encounter an error while streaming the response to the client) the Express default error handler closes the connection and fails the request.

It is difficult to really say without seeing a reproduction, but also difficult to formulate a fix without one as well, I hope you understand. I can certainly re-open this if one is provided to further evaluate, though!

**Comment by timexcession** [comment]
Thanks for you attention. If I pin down the issue, I'll come back to it too.
