### ISSUE TITLE
Remove trailing newline

### ISSUE THREAD

**Issue by niftylettuce** [pillarjs/finalhandler#9]
<https://github.com/pillarjs/finalhandler/blob/master/index.js#L92>

**Comment by niftylettuce** [comment]
Is there a way to turn this off?

**Comment by dougwilson** [comment]
That was added to Express after many hot debates a couple years ago, and we wont be changing that output any time soon.

Now, if you want to propose a way to specify your own content, like the existing PR that fizzled out without a response, that is fine, as then you can not have a new line in your response format.

**Comment by niftylettuce** [comment]
Is there reference to this debate publicly? @dougwilson

**Comment by dougwilson** [comment]
I will have to search for it it is either in the Express or Connect repo from years ago. I am on my phone and it is pretty much impossible to search on their mobile site. I will not be on a computer for a few days, so you'll either need to wait a few days for me to get back to you or you can try to find it.

Regardless, I am not changing the output format. Please pick up that PR to add the ability for custom output formats (or don't even use this module, as the more you customize it, the less you're using this module, really).

**Comment by niftylettuce** [comment]
cant we just pass an option to options object and set it default to true
Boolean?  `hasNewlinesAffixed`?  thatd be easy... like 3 LOC and u don't
need a version bump

**Comment by dougwilson** [comment]
Also, that response is HTML, and HTML collapses newlines, so newline literally make no difference, which is another reason we won't be removing the new line at the end.

**Comment by dougwilson** [comment]
If you want to make a PR, just finish off that render PR, please, because I want to add that functionality and it has the addition bonus in that it also solves your use-case. The a new line in HTML is such an implementation detail I would never accept exposing that in an option; just help us wrap up that render PR.

**Comment by niftylettuce** [comment]
It doesn't respect `Accept: application/json` requests though, it gives an HTML response

**Comment by niftylettuce** [comment]
In that case, it shouldn't give HTML, it should just do plaintext response, no?

**Comment by dougwilson** [comment]
Content negotiation is 100% optional in HTTP and this module does not do that, because if you want that level of control, you should not even bother using this module.

This module is here as a "last resort" style handler: on an error or something else that you have not taken the time to respond to in the way you want, this is designed to give some kind of response instead of letting the request hang.

If you are using Express or Connect, simply implement a 404 and an error handler in your app.

**Comment by dougwilson** [comment]
Plus, if you help push that render PR forward, then you can implement all the content negotiation you desire in the render method, so it works exactly hoe you want (this is exactly why I want to get that finished). Please, check out the PR, see the comments, and start working on a new PR to get them addressed (or probe the current author to see the status on it).

**Comment by niftylettuce** [comment]
Sorry crammed for time with day job and other side projects
